# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Mapping-Object.sln --ignore-failed-sources
    - name: Build lib
      run: dotnet build ./src/Mapping-Object/Mapping-Object.csproj --no-restore
    - name: Build lib
      run: dotnet build "./src/Mapping-Object Async/Mapping-Object Async.csproj" --no-restore
    - name: Build tests
      run: dotnet build "./src/Mapping-Object Tests/Mapping-Object Tests.csproj" --no-restore
    - name: Build tests
      run: dotnet build "./src/Mapping-Object Async Tests/Mapping-Object Async Tests.csproj" --no-restore
    - name: Test
      run: dotnet test ./src/Mapping-Object.sln --no-build --verbosity normal
